In [1]:
import time
import numpy as np
import cv2
import pandas as pd
import matplotlib.pyplot as plt
from scipy import signal
import os, errno
import glob

In [27]:
source = r"C:\Users\Daniellab\Desktop\Jorge_Analysis\Centroids_Relevant"
window = r"C:\Users\Daniellab\Desktop\Jorge_Analysis\In_Out_Refined"
outpath = r"C:\Users\Daniellab\Desktop\Jorge_Analysis\Centroid_Filtered"

In [28]:
csv_list = glob.glob(source + "\\*.csv")
csv_list = csv_list[:8] + csv_list[:]

'Experimental_1_0_52688.csv'

In [35]:
i = 0
for element in csv_list:
    df = pd.read_csv(source + "\\" + element[61:])
    if np.any(df.X_position.isnull()):
        print(element[61:-4], df.FrameNumber.values[-1])
        print(np.asarray(np.where(df.X_position.isnull())).ravel())
        i+=1

Experimental_1_0_52688 53391
[  0   1 471 472 473 475 476 477 478 479 480 482 483 484 485 486 487 696
 697 698 699 700 701 702 703]
Experimental_4_1_72340 72750
[0 1 2 3]
Experimental_7_0_36526 36805
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
 274 275 276 277 278 279]
Experimental_7_1_36846 37266
[  0   1   2 418 419 420]
Experimental_7_2_40443 40717
[  0   1 269 270 271 274]
Experimental_7_3_41552 41909
[  0   1   2 353 354 355 356 357]
Experimental_7_4_54607 54961
[  0   1   2   3   4 350 351 352 353 354]
Sham_10_0_2935 23638
[20698 20699 20700 20701 20702 20703]
Sham_14_1_2773 24216
[21433 21434 21435 21441 21442 21443]
Sham_16_8_29633 31062
[1413 1414 1415 1416 1417 1418 1419 1420 1421 1422 1423 1424 1425 1426
 1427 1428 1429]
Sham_16_9_31431 31801
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  16  17  18
  20  21  22  24  25  26  28  29  30  32  33  34 296 297 298 299 300 301
 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 