In [123]:
import time
import numpy as np
import cv2
import pandas as pd
import matplotlib.pyplot as plt
from scipy import signal
import os, errno
import glob

In [124]:
source = r"/Users/Mahad/Downloads/drive-download-20200317T004709Z-001/Centroids_Relevant"
window = r"/Users/Mahad/Downloads/drive-download-20200317T004709Z-001/In_Out_Refined"
outpath = r"/Users/Mahad/Downloads/drive-download-20200317T004709Z-001/Centroid_Filtered"

In [125]:
csv_list = glob.glob(source + "//*.csv")

In [126]:
i = 0
for element in csv_list:
    df = pd.read_csv(source + "//" + element[78:])
    if np.any(df.X_position.isnull()):
        print(element[78:-4], df.FrameNumber.values[-1])
        print(np.asarray(np.where(df.X_position.isnull())).ravel())
        i+=1

Sham_17_0_1417 1900
[0]
Experimental_7_4_54607 54961
[  0   1   2   3   4 350 351 352 353 354]
Experimental_7_1_36846 37266
[  0   1   2 418 419 420]
Sham_14_1_2773 24216
[21433 21434 21435 21441 21442 21443]
Sham_16_9_31431 31801
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  16  17  18
  20  21  22  24  25  26  28  29  30  32  33  34 296 297 298 299 300 301
 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 340
 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358
 359 360 361 362 363 364 365 366 367 368 369 370]
Experimental_7_3_41552 41909
[  0   1   2 353 354 355 356 357]
Experimental_4_1_72340 72750
[0 1 2 3]
Sham_16_8_29633 31062
[1413 1414 1415 1416 1417 1418 1419 1420 1421 1422 1423 1424 1425 1426
 1427 1428 1429]
Sham_7_0_63837 64125
[231 232 233 234 235 236 237 239 240 241 242 243 244 245 246 247 248 249
 250 251 252 253 254 255 256 257 258 259 260 261 262]
Experimental_7_0_36526 36805
[  0   1   2   3   4   5   6   7   8  

In [127]:
new_list = []
for element in csv_list:
    
    if not element[78:].startswith('Sham_18'):
        if not element[78:].startswith('Experiment_2_1'):
            if not element[78:].startswith('Sham_3_0'):
                if  not element[78:].startswith('Sham_1_16'):
                    if  not element[78:].startswith('Sham_1_19'):
                        if  not element[78:].startswith('Sham_10_0'):
                            if not element[78:].startswith('Sham_14_1'):
                                if not element[78:].startswith('Sham_17_0'):
                                
                                    new_list.append(element)
   

In [128]:
for element in new_list:
    if element[78:].startswith('Experimental_1_0'):
        start, end = 53188 , 53300
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
    
        df.to_csv(source + "//" + element[78:])
    elif element[78:].startswith('Experimental_4_1'):
        start, end = 72345 , 72750
        
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
        df.to_csv(source + "//" + element[78:])
    elif element[78:].startswith('Experimental_7_0'):
        start, end = 36544 , 36790
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
        df.to_csv(source + "//" + element[78:])
    elif element[78:].startswith('Experimental_7_1'):
        start, end = 36856 , 37200
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
        df.to_csv(source + "//" + element[78:])
    elif element[78:].startswith('Experimental_7_2'):
        start, end = 40450 , 40710
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
        df.to_csv(source + "//" + element[78:])
    elif element[78:].startswith('Experimental_7_3'):
        start, end = 41560 , 41900
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
        df.to_csv(source + "//" + element[78:])
    elif element[78:].startswith('Experimental_7_4'):
        start, end = 54620 , 54950
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
        df.to_csv(source + "//" + element[78:])
    elif element[78:].startswith('Sham_16_8'):
        start, end = 30900, 31010
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
        df.to_csv(source + "//" + element[78:])
    elif element[78:].startswith('Sham_16_9'):
        start, end = 31500, 31705
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
        df.to_csv(source + "//" + element[78:])
    elif element[78:].startswith('Sham_7_0'):
        start, end = 63837, 64050
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
        df.to_csv(source + "//" + element[78:])
    elif element[78:].startswith('Sham_7_1'):
        start, end = 65050, 65455
        df = pd.read_csv(source + "//" + element[78:])
        df = df[(df['FrameNumber'] >= start) & (df['FrameNumber'] < end)]
        df = df.reset_index()
        df = df.drop(columns=['Unnamed: 0', 'index'])
        df.to_csv(source + "//" + element[78:])
    df = pd.read_csv(source + "//" + element[78:])
    df.to_csv(source + "//" + element[78:])